"""PlantVillage training helper package."""

from .config import ExperimentConfig, set_seed
from .data import (
    AUG_TYPES,
    RandomAugImageFolder,
    get_aug_transform,
    load_base_dataset,
    split_dataset,
    create_dataloaders,
)
from .models import get_model
from .train import (
    train_one_epoch,
    eval_model,
    train_and_record,
    visualize_predictions,
    train_multiple_models,
    plot_model_val_compare,
    save_history,
    load_history,
)
from .compression import (
    apply_conv_pruning,
    build_quantized_dict,
    load_quantized_weights,
    print_huffman_like_ratio,
    collect_conv_sparsity,
    finetune_model,
    compute_storage_breakdown,
    plot_storage_breakdown,
    plot_confusion,
    plot_quant_centers,
    plot_finetune_compare,
)
from .paper_eval import (
    collect_predictions,
    compute_main_metrics,
    per_class_metrics_df,
    plot_confusion,
    top_confused_pairs,
    model_param_count,
    model_size_mb,
    huffman_estimated_size_mb,
    inference_latency_ms_per_img,
)

__all__ = [
    "ExperimentConfig",
    "set_seed",
    "AUG_TYPES",
    "RandomAugImageFolder",
    "get_aug_transform",
    "load_base_dataset",
    "split_dataset",
    "create_dataloaders",
    "get_model",
    "train_one_epoch",
    "eval_model",
    "train_and_record",
    "visualize_predictions",
    "train_multiple_models",
    "plot_model_val_compare",
    "save_history",
    "load_history",
    "apply_conv_pruning",
    "build_quantized_dict",
    "load_quantized_weights",
    "print_huffman_like_ratio",
    "collect_conv_sparsity",
    "finetune_model",
    "compute_storage_breakdown",
    "plot_storage_breakdown",
    "plot_confusion",
    "plot_quant_centers",
    "plot_finetune_compare",
    "collect_predictions",
    "compute_main_metrics",
    "per_class_metrics_df",
    "plot_confusion",
    "top_confused_pairs",
    "model_param_count",
    "model_size_mb",
    "huffman_estimated_size_mb",
    "inference_latency_ms_per_img",
]
